# Project setup
OBJNAME :=  mandroid
CPPC :=     g++
CPPFLAGS := -Werror -Wall -std=c++17 -g
LD :=       g++
LDFLAGS :=  -lSDL2 -lSDL2_mixer \
            -L/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf -lpython3.7
SRC :=      $(wildcard src/*.cpp)
INCDIRS :=  include /usr/include/python3.7 /usr/include/python3.7m

# Helper Targets
.PHONY : all
all : $(OBJNAME)

.PHONY : clean
clean :
	rm -rf obj
	rm -rf $(OBJNAME)

# Autogenerated stuff
INC :=      $(addprefix -I,$(INCDIRS))
OBJS :=     $(subst cpp,o,$(subst src,obj,$(SRC)))

obj/main.o : src/main.cpp include/Tests.hpp
	mkdir -p obj
	$(CPPC) $(CPPFLAGS) $(INC) -o $@ -c $<

obj/%.o : src/%.cpp
	mkdir -p obj
	$(CPPC) $(CPPFLAGS) $(INC) -o $@ -c $<

# Main targets
$(OBJNAME) : $(OBJS)
	$(LD) -o $@ $(OBJS) $(LDFLAGS)

.PHONY : install
install : $(OBJNAME)
	mkdir -p /opt/mandroid
	mkdir -p /opt/mandroid/src
	cp $(OBJNAME) /opt/mandroid/
	cp -rf audio /opt/mandroid
	cp src/pwm.py /opt/mandroid/src
	cp src/listen.py /opt/mandroid/src
	cp dict.txt /opt/mandroid
	ln -s /opt/mandroid/$(OBJNAME) /usr/bin/$(OBJNAME)
	cp src/mandroid.service /etc/systemd/system/mandroid.service
	chmod 644 /etc/systemd/system/mandroid.service
	systemctl enable mandroid.service

.PHONY : uninstall
uninstall :
	rm -rf /opt/mandroid
	rm -rf /usr/bin/mandroid
	systemctl disable mandroid.service
