# Project setup
OBJNAME :=  mandroid
CPPC :=     g++
CPPFLAGS := -O2 -Werror -Wall -std=c++17
LD :=       g++
LDFLAGS :=  -lSDL2 -lSDL2_mixer
SRC :=      $(wildcard src/*.cpp)
INCDIRS :=  include

# Helper Targets
.PHONY : all
all : $(OBJNAME)

.PHONY : clean
clean :
	rm -rf obj
	rm -rf $(OBJNAME)

# Autogenerated stuff
INC :=      $(addprefix -I,$(INCDIRS))
OBJS :=     $(subst cpp,o,$(subst src,obj,$(SRC)))

obj/main.o : src/main.cpp include/Tests.hpp
	mkdir -p obj
	$(CPPC) $(CPPFLAGS) $(INC) -o $@ -c $<

obj/%.o : src/%.cpp
	mkdir -p obj
	$(CPPC) $(CPPFLAGS) $(INC) -o $@ -c $<

# Main targets
$(OBJNAME) : $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)
